/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rbkmoney.geck.serializer.domain;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import javax.annotation.Generated;
import java.util.*;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2020-07-09")
public class MapListTest implements org.apache.thrift.TBase<MapListTest, MapListTest._Fields>, java.io.Serializable, Cloneable, Comparable<MapListTest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MapListTest");

  private static final org.apache.thrift.protocol.TField LIST_MAP_STRING_FIELD_DESC = new org.apache.thrift.protocol.TField("listMapString", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final SchemeFactory STANDARD_SCHEME_FACTORY = new MapListTestStandardSchemeFactory();
  private static final SchemeFactory TUPLE_SCHEME_FACTORY = new MapListTestTupleSchemeFactory();

  public List<String> listMapString; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LIST_MAP_STRING((short)1, "listMapString");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LIST_MAP_STRING
          return LIST_MAP_STRING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LIST_MAP_STRING, new org.apache.thrift.meta_data.FieldMetaData("listMapString", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MapListTest.class, metaDataMap);
  }

  public MapListTest() {
  }

  public MapListTest(
    List<String> listMapString)
  {
    this();
    this.listMapString = listMapString;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MapListTest(MapListTest other) {
    if (other.isSetListMapString()) {
      List<String> __this__listMapString = new ArrayList<String>(other.listMapString);
      this.listMapString = __this__listMapString;
    }
  }

  public MapListTest deepCopy() {
    return new MapListTest(this);
  }

  @Override
  public void clear() {
    this.listMapString = null;
  }

  public int getListMapStringSize() {
    return (this.listMapString == null) ? 0 : this.listMapString.size();
  }

  public java.util.Iterator<String> getListMapStringIterator() {
    return (this.listMapString == null) ? null : this.listMapString.iterator();
  }

  public void addToListMapString(String elem) {
    if (this.listMapString == null) {
      this.listMapString = new ArrayList<String>();
    }
    this.listMapString.add(elem);
  }

  public List<String> getListMapString() {
    return this.listMapString;
  }

  public MapListTest setListMapString(List<String> listMapString) {
    this.listMapString = listMapString;
    return this;
  }

  public void unsetListMapString() {
    this.listMapString = null;
  }

  /** Returns true if field listMapString is set (has been assigned a value) and false otherwise */
  public boolean isSetListMapString() {
    return this.listMapString != null;
  }

  public void setListMapStringIsSet(boolean value) {
    if (!value) {
      this.listMapString = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LIST_MAP_STRING:
      if (value == null) {
        unsetListMapString();
      } else {
        setListMapString((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LIST_MAP_STRING:
      return getListMapString();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LIST_MAP_STRING:
      return isSetListMapString();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MapListTest)
      return this.equals((MapListTest)that);
    return false;
  }

  public boolean equals(MapListTest that) {
    if (that == null)
      return false;

    boolean this_present_listMapString = true && this.isSetListMapString();
    boolean that_present_listMapString = true && that.isSetListMapString();
    if (this_present_listMapString || that_present_listMapString) {
      if (!(this_present_listMapString && that_present_listMapString))
        return false;
      if (!this.listMapString.equals(that.listMapString))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetListMapString()) ? 131071 : 524287);
    if (isSetListMapString())
      hashCode = hashCode * 8191 + listMapString.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(MapListTest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetListMapString()).compareTo(other.isSetListMapString());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetListMapString()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.listMapString, other.listMapString);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public _Fields[] getFields() {
    return _Fields.values();
  }

  public Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> getFieldMetaData() {
    return metaDataMap;
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MapListTest(");
    boolean first = true;

    sb.append("listMapString:");
    if (this.listMapString == null) {
      sb.append("null");
    } else {
      sb.append(this.listMapString);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MapListTestStandardSchemeFactory implements SchemeFactory {
    public MapListTestStandardScheme getScheme() {
      return new MapListTestStandardScheme();
    }
  }

  private static class MapListTestStandardScheme extends StandardScheme<MapListTest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MapListTest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LIST_MAP_STRING
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list168 = iprot.readListBegin();
                struct.listMapString = new ArrayList<String>(_list168.size);
                String _elem169;
                for (int _i170 = 0; _i170 < _list168.size; ++_i170)
                {
                  _elem169 = iprot.readString();
                  struct.listMapString.add(_elem169);
                }
                iprot.readListEnd();
              }
              struct.setListMapStringIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MapListTest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.listMapString != null) {
        oprot.writeFieldBegin(LIST_MAP_STRING_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.listMapString.size()));
          for (String _iter171 : struct.listMapString)
          {
            oprot.writeString(_iter171);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MapListTestTupleSchemeFactory implements SchemeFactory {
    public MapListTestTupleScheme getScheme() {
      return new MapListTestTupleScheme();
    }
  }

  private static class MapListTestTupleScheme extends TupleScheme<MapListTest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MapListTest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetListMapString()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetListMapString()) {
        {
          oprot.writeI32(struct.listMapString.size());
          for (String _iter172 : struct.listMapString)
          {
            oprot.writeString(_iter172);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MapListTest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list173 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.listMapString = new ArrayList<String>(_list173.size);
          String _elem174;
          for (int _i175 = 0; _i175 < _list173.size; ++_i175)
          {
            _elem174 = iprot.readString();
            struct.listMapString.add(_elem174);
          }
        }
        struct.setListMapStringIsSet(true);
      }
    }
  }

  private static <S extends IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

